### PR TITLE
Added implicit operators to automatically cast to and from ReactiveVariable

### PR DESCRIPTION
**Pull request by Giorgi**
Instead of 
```
[Test]
public void Square()
{
    var input = new ReactiveVariable<int>(1);
    var inputSquared = new ReactiveExpression<int>(() => input.Value * input.Value);
    inputSquared.Subscribe(getSquare => Console.WriteLine("square = " + getSquare()));

    input.Value = 2;
    input.Value = 3;
}
```

you can now write 
```

[Test]
public void SquareWithImplicitOperators()
{
    ReactiveVariable<int> input = 1;
    var inputSquared = new ReactiveExpression<int>(() => input * input);
    inputSquared.Subscribe(getSquare => Console.WriteLine("square = " + getSquare()));

    input = 2;
    input = 3;
}
```

### CODE REVIEW

**Comment by keyboardDrummer** [comment]
Hi there,

Thanks for you contribution. Could you provide a motivation for this change? Personally I'm a bit wary of using implicits to avoid confusion. I'm not really sure what the consensus is on how to use them. I've read that for Scala for example it's considered bad practice to define implicit conversion for types the library did not define itself. What's your opinion on this?

Regards,
Remy

**Comment by Giorgi** [comment]
My main motivation was to make the code less verbose. For me `new ReactiveVariable<int>(1)` is too noisy similar to new `Nullable<int>(1)`. I am not familiar with Scala in depth but as ReactiveVariable enriches `T` I think it reasonable to provide automatic conversion between them

**Comment by engdata** [comment]
I haven't examined the source code thoroughly, but I believe having the ReactiveVariable created implicitly would be problematic since a new object is created and any existing event bindings, observables, and references would be lost.

**Comment by Giorgi** [comment]
@engdata You are right, I didn't think about that. The new test was green but it doesn't have any assert statements so I thought it was passing. I guess this PR can be closed. @keyboardDrummer What do you think about `ToReactive` extension method?

**Comment by keyboardDrummer** [comment]
@engdata Yes the example shown by Giorgi wouldn't work.

I think it's safe to conclude that an implicit conversion from ```T``` to ```ReactiveVariable<T>``` would be confusing.

@Giorgi I agree that it's a bit noisy.

Let's look at two types of noise. 
1) Creating a reactive, for example: ```new ReactiveVariable<int>(1)```
2) Using a reactive, for example the ```input.Value``` in 
```new ReactiveExpression<int>(() => input.Value * input.Value)```

##### Creating a reactive
This noise is partly because C# still requires the type argument for constructors of generic types, but since that's not getting changed any time soon let's look for a solution.

What about adding some factory methods such as ```Reactive.Variable<T>(T value)``` and ```Reactive.Expression<T>(Func<T> value)```?

so ```new ReactiveVariable<T>(...)``` becomes ```Reactive.Variable(...)```
and ```new ReactiveExpression<T>(...)``` becomes ```Reactive.Expression(...)```

Your suggestion for adding an extension method such as ```ToReactive``` also sounds promising. Although I think that would mostly be nice for creating reactive variables, but not expressions. @Giorgi Would you prefer this over the factory methods?

##### Using a reactive
For this noise I think implicits are interesting. It's a trade-off between less noise and more safety though. If you add only implicit conversions from reactive objects to their value, that would allow you to write 
```Reactive.Expression(() => input.Value * input.Value)``` 
as simply 
```Reactive.Expression(() => input * input)```. 

It's a bit dangerous though because then the following two programs would not be equivalent. The first program would work while the second would not.
```
var input = Reactive.Variable(1);
var square = Reactive.Expression(() => input * input);
```
```
var input = Reactive.Variable(1);
int temp = input;
var square = Reactive.Expression(() => temp * temp);
````

For me the above example shows that implicits can be somewhat dangerous, because code that looks the same really is not. What's your opinion here?

**Comment by engdata** [comment]
I think the implicit conversion to the generic type is actually a good feature since the variable type is visible in the immediate scope anyway - and it makes the type more composable within basic CLR code.

Personally, I would stick to the constructor and value syntax - as it is easy to understand the intent and really not all that intrusive.

**Comment by Giorgi** [comment]
@keyboardDrummer This is what I think:

**Creating a reactive**

I prefer extension methods over factory methods because I find them easier to read but I don't like that it pollutes intellisense and it won't work for expression as you have mentioned.

**Using a reactive**

You have a good point there but I think that quite an edge case. Between readability and such edge cases I would probably choose readability. One more possibility is to accept an `Expression` instead of `Func` and if there are no reactive variables throw an exception with clear message so that's it's quick and easier to diagnose such cases. It won't catch all cases but it can also be useful for providing extended diagnostic information.

**Comment by keyboardDrummer** [comment]
Alright I put in the extension method and one conversion from ReactiveVariable<T> to T. I'll keep your suggestion about using an Expression<T> instead of a Func<T> in mind but I'm not using that yet.

**Pull request closed without merging**
